task3a/config/routes.rb
Rails.application.routes.draw do
  resources :funds do
    resources :holdings
  end
  root "funds#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

task3a/app/models/fund.rb
class Fund
  include Mongoid::Document
  field :code, type: String
  field :name, type: String
  field :date, type: String
  field :t_value, type: Float
  field :t_perc, type: Float
  embeds_many :holdings
end

task3a/app/models/holding.rb
class Holding
  include Mongoid::Document
  field :name, type: String
  field :isin, type: String
  field :qty, type: Float
  field :value, type: Float
  field :perc, type: Float
  field :rating, type: String
  field :remarks, type: String
  embedded_in :fund
end

task3a/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

task3a/app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

  #method to get all the fund records which are in funds colletion
  def index
    @funds = Fund.all
  end

  #method to show the specified fund
  def show
  end

  # method to create a new empty fund
  def new
    @fund = Fund.new
  end

  # method to edit the specified fund
  def edit
  end

  # method to create new fund
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # method to update the specified fund
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # method to delete the specified fund
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # method to set the specified fund used by show ,update, edit and  destroy methods
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Method to whitelist the required params.
    def fund_params
      params.require(:fund).permit(:code, :name, :date, :t_value, :t_perc)
    end
end

task3a/app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  before_action :set_holding, only: [:show, :edit, :update, :destroy]

  #method to display all the holdings of specified fund
  def index
    @fund = Fund.find(params[:fund_id])
    @holdings = @fund.holdings.all
  end

  #method to show the specified holding in specified fund
  def show
  end

  #method to create an empty holding instance
  def new 
    @holding = Holding.new
  end

 #method to edit the specified holding in specified fund
  def edit
  end

  # method to create a new holding in specified fund
  def create
    @fund = Fund.find( params[:fund_id] )
    @holding = @fund.holdings.new(holding_params)    
      if @holding.save
         redirect_to fund_holdings_path, notice: 'Holding was successfully created.' 
      else
         render :new 
      end
    end

 #method to update the specified holding in specified fund
  def destroy
    @holding.update(holding_params)
    respond_to do |format|
      format.html { redirect_to holdings_url, notice: 'Holding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 #method to delete the specified holding in specified fund
  def destroy
    @holding.destroy
    respond_to do |format|
      format.html { redirect_to holdings_url, notice: 'Holding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Method to set the specified fund and specified holding used by show,edit,update and destroy methods only
    def set_holding
      @fund = Fund.find(params[:fund_id])
      @holding = @fund.Holdings.find(params[:id])
    end

    # Whitelisting the only required parameters
    def holding_params
      params.require(:holding).permit(:name, :isin, :qty, :value, :perc, :rating, :remarks)
    end
end

task3a/app/helpers/application_helper.rb
module ApplicationHelper
end

task3a/app/helpers/funds_helper.rb
module FundsHelper
end

task3a/app/helpers/holdings_helper.rb
module HoldingsHelper
end

task3a/app/views/funds/_form.html.erb
<%= form_with(model: fund, local: true ,class:"well") do |form| %>
  <% if fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code , class:"col-md-3"%>
    <%= form.text_field :code, id: :fund_code, class:"col-md-3" %>
  </div>

  <div >
    <%= form.label :name , class:"col-md-3"%>
    <%= form.text_field :name, id: :fund_name, class:"col-md-3" %>
  </div>
<br><br><br>
  <div >
    <%= form.label :date , class:"col-md-3"%>
    <%= form.text_field :date, id: :fund_date, class:"col-md-3" %>
  </div>
<br>
  <div >
    <%= form.label :t_value , class:"col-md-3"%>
    <%= form.text_field :t_value, id: :fund_t_value, class:"col-md-3" %>
  </div>

  <div >
    <%= form.label :t_perc, class:"col-md-3" %>
    <%= form.text_field :t_perc, id: :fund_t_perc, class:"col-md-3" %>
  </div>
<br><br><br><br><br>
  <div >
    <%= form.submit %>
  </div>
<% end %>

task3a/app/views/funds/edit.html.erb
<h1>Editing Fund</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

task3a/app/views/funds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funds</h1>
<%= link_to 'New Fund', new_fund_path ,class:"label label-info" %>
<table class="table table-bordered table-striped"> 
  <thead>
    <tr class="heading">
      <th>Code</th>
      <th>Name</th>
      <th>Date</th>
      <th>T value</th>
      <th>T perc</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @funds.each do |fund| %>
      <tr>
        <td><%= fund.code %></td>
        <td><%= fund.name %></td>
        <td><%= fund.date %></td>
        <td><%= fund.t_value %></td>
        <td><%= fund.t_perc %></td>
        <td><%= link_to 'Show', fund , class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_fund_path(fund),class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', fund, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        <td><%= link_to 'Add Holdings', new_fund_holding_path(fund.id),  class:"btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

task3a/app/views/funds/new.html.erb
<h1>New Fund</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Back', funds_path %>

task3a/app/views/funds/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-bordered table-striped"> 
  <tbody>
    <tr>
      <td><p><strong>Code:</strong></td>
      <td><%= @fund.code %></p></td>
    </tr>

      <tr>
      <td><p><strong>Name:</strong></td>
      <td><%= @fund.name %></p></td>
    </tr>
    
    <tr>
      <td><p><strong>Date:</strong></td>
      <td><%= @fund.date %></p></td>
    </tr>
    
    <tr>
      <td><p><strong>Total Value:</strong></td>
      <td><%= @fund.t_value %></p></td>
    </tr>
    
    <tr>
      <td><p><strong>Percentage:</strong></td>
      <td><%= @fund.t_perc %></p></td>
    </tr>
  </tbody>
</table>

<%= link_to 'View Holdings of this fund' ,fund_holdings_path(@fund),class:"btn btn-primary" %> |
<%= link_to 'Edit', edit_fund_path(@fund),class:"btn btn-warning" %> |
<%= link_to 'Back', funds_path ,class:"btn btn-info" %>

task3a/app/views/holdings/_form.html.erb
<%= form_for :holding , url: fund_holdings_path , method: :post  do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :holding_name %>
  </div>

  <div class="field">
    <%= form.label :isin %>
    <%= form.text_field :isin, id: :holding_isin %>
  </div>

  <div class="field">
    <%= form.label :qty %>
    <%= form.text_field :qty, id: :holding_qty %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :holding_value %>
  </div>

  <div class="field">
    <%= form.label :perc %>
    <%= form.text_field :perc, id: :holding_perc %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating, id: :holding_rating %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_field :remarks, id: :holding_remarks %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

task3a/app/views/holdings/edit.html.erb
<h1>Editing Holding</h1>

<%= render 'form', holding: @holding %>

<%= link_to 'Show', @holding %> |
<%= link_to 'Back', holdings_path %>

task3a/app/views/holdings/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @fund.code%> Holdings</h2>

<table  class="table table-bordered table-striped">
  <thead>
    <tr>
      
      <th>Name</th>
      <th>Isin</th>
      <th>Qty</th>
      <th>Value</th>
      <th>Perc</th>
      <th>Rating</th>
      <th>Remarks</th>
    </tr>
  </thead>

  <tbody>
    <% @holdings.each do |holding| %>
      <tr>
        <td><%= holding.name %></td>
        <td><%= holding.isin %></td>
        <td><%= holding.qty %></td>
        <td><%= holding.value %></td>
        <td><%= holding.perc %></td>
        <td><%= holding.rating %></td>
        <td><%= holding.remarks %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

task3a/app/views/holdings/new.html.erb
<h1>New Holding</h1>

<%= render 'form', holding: @holding %>

<%= link_to 'Back', fund_holdings_path %>

task3a/app/views/holdings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @holding.name %>
</p>

<p>
  <strong>Isin:</strong>
  <%= @holding.isin %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @holding.qty %>
</p>

<p>
  <strong>Value:</strong>
  <%= @holding.value %>
</p>

<p>
  <strong>Perc:</strong>
  <%= @holding.perc %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @holding.rating %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @holding.remarks %>
</p>

<%= link_to 'Edit', edit_holding_path(@holding) %> |
<%= link_to 'Back', holdings_path %>

task3a/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task3a</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container text-center">
    <%= yield %>
  </body>
</html>